services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        Habu\TaskSchedulerBundle\Interfaces\ProducerInterface:
            tags: ['task_scheduler.producer']

        Habu\TaskSchedulerBundle\Interfaces\TaskInterface:
            tags: ['task_scheduler.task']
            public: true

    # Unnamed services that should get autowired
    Habu\TaskSchedulerBundle\Service\SchedulerService: ['@task_scheduler.producer_locator']
    Habu\TaskSchedulerBundle\Worker\Worker: ['@task_scheduler.task_locator']

    # Included default task producers
    task_scheduler.producer.transient:
        class: Habu\TaskSchedulerBundle\Producer\TransientProducer

    task_scheduler.producer.none:
        class: Habu\TaskSchedulerBundle\Producer\NoneProducer

    # Service locator services, used to isolate tagged
    # services of that kind
    task_scheduler.task_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator

    task_scheduler.producer_locator:
        class: Symfony\Component\DependencyInjection\ServiceLocator